# screw this event
target-practice:
  enabled: true
  area: "world,615,131,411,620,136,416"
  sphere: "world,615,131,411"
  max: 30

apple-bobbing:
  enabled: true
  area: "world,601,131,424,595,134,432"
  max: 30

underwater-animals:
  enabled: false
  area: "world,601,131,424,595,134,432"
  max: 60

prison-mine:
  area: "world,601,131,424,595,134,432"