# screw this event
target-practice:
  enabled: true
  area: "world,136,-47,342,67,-42,3802"
  sphere: "world,99,-47,346"
  max: 30

apple-bobbing:
  enabled: true
  area: "world,175,-44,261,195,-51,281"
  max: 30

underwater-animals:
  enabled: false
  area: "world,601,131,424,595,134,432"
  max: 60

prison-mine:
  area: "world,-39,-60,204,-3,-50,163"