# screw this event
target-practice:
  enabled: true
  area: "event_new,257,61,65,184,68,113"
  sphere: "event_new,220,62,65"
  max: 80

apple-bobbing:
  enabled: true
  area: "event_new,297,64,-15,316,58,5"
  max: 30

underwater-animals:
  enabled: false
  area: "event_new,0,0,0,1,1,1"
  max: 60

prison-mine:
  area: "event_new,82,48,-114,118,57,-73"