target-practice:
  enabled: true
  area: "world,615,131,411,620,136,416"

apple-bobbing:
  enabled: true
  area: "world,601,131,424,595,134,432"
  max: 30

underwater-animals:
  enabled: true
  area: "world,601,131,424,595,134,432"
  max: 60