name: LumaCarnival
main: dev.jsinco.lumacarnival.CarnivalMain
version: 2024
api-version: 1.20
depend:
  - LumaItems
softdepend:
  - EvenMoreFish
  - JetsPrisonMines
commands:
  lumacarnival:
    description: test